### ISSUE TITLE
Circuit.hpp - getter methods

### ISSUE THREAD

**Issue by alexwangtech** [geochrist/dctk#1]
In file /src/Circuit.hpp, I noticed that the getter methods require float arguments. I was wondering if those are how it's supposed to be?
![getter-methods](https://user-images.githubusercontent.com/48783729/68559192-195e0e80-040a-11ea-8ef4-b0da363be5f3.png)

**Comment by geochrist** [comment]
It’s a mistake.  I’ll fix it soon. 

George

**Comment by geochrist** [comment]
Fixed now.  Thanks for reporting!
